#:schema node_modules/wrangler/config-schema.json
name = "nikomaru-page-resources"
compatibility_date = "2024-06-20"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"
[placement]
mode = "smart"

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#r2-buckets
[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'nikomaru-page-resources'
preview_bucket_name = 'nikomaru-page-resources'
